// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	types "github.com/MunifTanjim/pushport/internal/db/types"
)

type App struct {
	ID                 string
	Name               string
	EncTokenHash       []byte
	IsPublic           bool
	KeyVersion         int64
	MinKeyVersion      int64
	TurnstileSiteKey   types.NullString
	EncTurnstileSecret []byte
	CreatedAt          int64
	UsagePlanID        types.NullString
}

type AppCredential struct {
	AppID     string
	Transport string
	EncBlob   []byte
}

type AppUsagePlan struct {
	ID               string
	AppID            types.NullString
	Name             string
	IsDefault        bool
	CreatedAt        int64
	PushPerMin       int64
	PushDailyQuota   int64
	RegisterPerMin   int64
	RegisterBurst    int64
	RegisterIpPerMin int64
	RegisterIpBurst  int64
	SubscribePerMin  int64
	SubscribeBurst   int64
}

type Instance struct {
	ID           string
	AppID        string
	Label        string
	EncTokenHash []byte
	CreatedAt    int64
	UsagePlanID  types.NullString
}

type InstanceUsagePlan struct {
	ID             string
	AppID          string
	InstanceID     types.NullString
	Name           string
	IsDefault      bool
	CreatedAt      int64
	PushPerMin     int64
	PushBurst      int64
	PushDailyQuota int64
}

type Setting struct {
	ID               int64
	RetryMaxAttempts int64
	RetryBaseBackoff string
	RetryMaxBackoff  string
	AuthFailIpPerMin int64
	AuthFailIpBurst  int64
}

type UsageCounter struct {
	Scope string
	Date  types.Date
	Count int64
}
