// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	types "github.com/MunifTanjim/pushport/internal/db/types"
)

const assignAppUsagePlan = `-- name: AssignAppUsagePlan :execrows
UPDATE app SET usage_plan_id = ?1 WHERE id = ?2
`

type AssignAppUsagePlanParams struct {
	UsagePlanID types.NullString
	ID          string
}

func (q *Queries) AssignAppUsagePlan(ctx context.Context, arg AssignAppUsagePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignAppUsagePlan, arg.UsagePlanID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const assignInstanceUsagePlan = `-- name: AssignInstanceUsagePlan :execrows
UPDATE instance SET usage_plan_id = ?1 WHERE id = ?2
`

type AssignInstanceUsagePlanParams struct {
	UsagePlanID types.NullString
	ID          string
}

func (q *Queries) AssignInstanceUsagePlan(ctx context.Context, arg AssignInstanceUsagePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignInstanceUsagePlan, arg.UsagePlanID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearAppTurnstile = `-- name: ClearAppTurnstile :execrows
UPDATE app SET turnstile_site_key = NULL, enc_turnstile_secret = NULL WHERE id = ?1
`

func (q *Queries) ClearAppTurnstile(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearAppTurnstile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countApps = `-- name: CountApps :one
SELECT COUNT(*) FROM app
`

func (q *Queries) CountApps(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInstances = `-- name: CountInstances :one
SELECT COUNT(*) FROM instance
`

func (q *Queries) CountInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInstances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :exec
INSERT INTO app (id, name, created_at)
VALUES (?1, ?2, ?3)
`

type CreateAppParams struct {
	ID        string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const createAppUsagePlan = `-- name: CreateAppUsagePlan :exec
INSERT INTO app_usage_plan (id, app_id, name, push_per_min, push_daily_quota, register_per_min, register_burst, register_ip_per_min, register_ip_burst, subscribe_per_min, subscribe_burst, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type CreateAppUsagePlanParams struct {
	ID               string
	AppID            types.NullString
	Name             string
	PushPerMin       int64
	PushDailyQuota   int64
	RegisterPerMin   int64
	RegisterBurst    int64
	RegisterIpPerMin int64
	RegisterIpBurst  int64
	SubscribePerMin  int64
	SubscribeBurst   int64
	CreatedAt        int64
}

func (q *Queries) CreateAppUsagePlan(ctx context.Context, arg CreateAppUsagePlanParams) error {
	_, err := q.db.ExecContext(ctx, createAppUsagePlan,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.PushPerMin,
		arg.PushDailyQuota,
		arg.RegisterPerMin,
		arg.RegisterBurst,
		arg.RegisterIpPerMin,
		arg.RegisterIpBurst,
		arg.SubscribePerMin,
		arg.SubscribeBurst,
		arg.CreatedAt,
	)
	return err
}

const createDefaultAppUsagePlan = `-- name: CreateDefaultAppUsagePlan :exec
INSERT INTO app_usage_plan (id, name, is_default, push_per_min, push_daily_quota, register_per_min, register_burst, register_ip_per_min, register_ip_burst, subscribe_per_min, subscribe_burst, created_at)
VALUES (?1, ?2, TRUE, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
`

type CreateDefaultAppUsagePlanParams struct {
	ID               string
	Name             string
	PushPerMin       int64
	PushDailyQuota   int64
	RegisterPerMin   int64
	RegisterBurst    int64
	RegisterIpPerMin int64
	RegisterIpBurst  int64
	SubscribePerMin  int64
	SubscribeBurst   int64
	CreatedAt        int64
}

func (q *Queries) CreateDefaultAppUsagePlan(ctx context.Context, arg CreateDefaultAppUsagePlanParams) error {
	_, err := q.db.ExecContext(ctx, createDefaultAppUsagePlan,
		arg.ID,
		arg.Name,
		arg.PushPerMin,
		arg.PushDailyQuota,
		arg.RegisterPerMin,
		arg.RegisterBurst,
		arg.RegisterIpPerMin,
		arg.RegisterIpBurst,
		arg.SubscribePerMin,
		arg.SubscribeBurst,
		arg.CreatedAt,
	)
	return err
}

const createDefaultInstanceUsagePlan = `-- name: CreateDefaultInstanceUsagePlan :exec
INSERT INTO instance_usage_plan (id, app_id, name, is_default, push_per_min, push_burst, push_daily_quota, created_at)
VALUES (?1, ?2, ?3, TRUE, ?4, ?5, ?6, ?7)
`

type CreateDefaultInstanceUsagePlanParams struct {
	ID             string
	AppID          string
	Name           string
	PushPerMin     int64
	PushBurst      int64
	PushDailyQuota int64
	CreatedAt      int64
}

func (q *Queries) CreateDefaultInstanceUsagePlan(ctx context.Context, arg CreateDefaultInstanceUsagePlanParams) error {
	_, err := q.db.ExecContext(ctx, createDefaultInstanceUsagePlan,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.PushPerMin,
		arg.PushBurst,
		arg.PushDailyQuota,
		arg.CreatedAt,
	)
	return err
}

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instance (id, app_id, label, enc_token_hash, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateInstanceParams struct {
	ID           string
	AppID        string
	Label        string
	EncTokenHash []byte
	CreatedAt    int64
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createInstance,
		arg.ID,
		arg.AppID,
		arg.Label,
		arg.EncTokenHash,
		arg.CreatedAt,
	)
	return err
}

const createInstanceUsagePlan = `-- name: CreateInstanceUsagePlan :exec
INSERT INTO instance_usage_plan (id, app_id, instance_id, name, push_per_min, push_burst, push_daily_quota, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type CreateInstanceUsagePlanParams struct {
	ID             string
	AppID          string
	InstanceID     types.NullString
	Name           string
	PushPerMin     int64
	PushBurst      int64
	PushDailyQuota int64
	CreatedAt      int64
}

func (q *Queries) CreateInstanceUsagePlan(ctx context.Context, arg CreateInstanceUsagePlanParams) error {
	_, err := q.db.ExecContext(ctx, createInstanceUsagePlan,
		arg.ID,
		arg.AppID,
		arg.InstanceID,
		arg.Name,
		arg.PushPerMin,
		arg.PushBurst,
		arg.PushDailyQuota,
		arg.CreatedAt,
	)
	return err
}

const deleteAppCredential = `-- name: DeleteAppCredential :exec
DELETE FROM app_credential WHERE app_id = ?1 AND transport = ?2
`

type DeleteAppCredentialParams struct {
	AppID     string
	Transport string
}

func (q *Queries) DeleteAppCredential(ctx context.Context, arg DeleteAppCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteAppCredential, arg.AppID, arg.Transport)
	return err
}

const deleteAppUsagePlan = `-- name: DeleteAppUsagePlan :execrows
DELETE FROM app_usage_plan WHERE id = ?1
`

func (q *Queries) DeleteAppUsagePlan(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAppUsagePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInstance = `-- name: DeleteInstance :execrows
DELETE FROM instance WHERE id = ?1
`

func (q *Queries) DeleteInstance(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInstanceUsagePlan = `-- name: DeleteInstanceUsagePlan :execrows
DELETE FROM instance_usage_plan WHERE id = ?1 AND app_id = ?2
`

type DeleteInstanceUsagePlanParams struct {
	ID    string
	AppID string
}

func (q *Queries) DeleteInstanceUsagePlan(ctx context.Context, arg DeleteInstanceUsagePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInstanceUsagePlan, arg.ID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUsageCountersBefore = `-- name: DeleteUsageCountersBefore :exec
DELETE FROM usage_counter WHERE date < ?1
`

func (q *Queries) DeleteUsageCountersBefore(ctx context.Context, date types.Date) error {
	_, err := q.db.ExecContext(ctx, deleteUsageCountersBefore, date)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, name, enc_token_hash, is_public, key_version, min_key_version, turnstile_site_key, enc_turnstile_secret, created_at, usage_plan_id FROM app WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncTokenHash,
		&i.IsPublic,
		&i.KeyVersion,
		&i.MinKeyVersion,
		&i.TurnstileSiteKey,
		&i.EncTurnstileSecret,
		&i.CreatedAt,
		&i.UsagePlanID,
	)
	return i, err
}

const getAppUsagePlan = `-- name: GetAppUsagePlan :one
SELECT id, app_id, name, is_default, created_at, push_per_min, push_daily_quota, register_per_min, register_burst, register_ip_per_min, register_ip_burst, subscribe_per_min, subscribe_burst FROM app_usage_plan WHERE id = ?
`

func (q *Queries) GetAppUsagePlan(ctx context.Context, id string) (AppUsagePlan, error) {
	row := q.db.QueryRowContext(ctx, getAppUsagePlan, id)
	var i AppUsagePlan
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.PushPerMin,
		&i.PushDailyQuota,
		&i.RegisterPerMin,
		&i.RegisterBurst,
		&i.RegisterIpPerMin,
		&i.RegisterIpBurst,
		&i.SubscribePerMin,
		&i.SubscribeBurst,
	)
	return i, err
}

const getDefaultAppUsagePlan = `-- name: GetDefaultAppUsagePlan :one
SELECT id, app_id, name, is_default, created_at, push_per_min, push_daily_quota, register_per_min, register_burst, register_ip_per_min, register_ip_burst, subscribe_per_min, subscribe_burst FROM app_usage_plan WHERE is_default = TRUE
`

func (q *Queries) GetDefaultAppUsagePlan(ctx context.Context) (AppUsagePlan, error) {
	row := q.db.QueryRowContext(ctx, getDefaultAppUsagePlan)
	var i AppUsagePlan
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.PushPerMin,
		&i.PushDailyQuota,
		&i.RegisterPerMin,
		&i.RegisterBurst,
		&i.RegisterIpPerMin,
		&i.RegisterIpBurst,
		&i.SubscribePerMin,
		&i.SubscribeBurst,
	)
	return i, err
}

const getDefaultInstanceUsagePlan = `-- name: GetDefaultInstanceUsagePlan :one
SELECT id, app_id, instance_id, name, is_default, created_at, push_per_min, push_burst, push_daily_quota FROM instance_usage_plan WHERE app_id = ?1 AND is_default = TRUE
`

func (q *Queries) GetDefaultInstanceUsagePlan(ctx context.Context, appID string) (InstanceUsagePlan, error) {
	row := q.db.QueryRowContext(ctx, getDefaultInstanceUsagePlan, appID)
	var i InstanceUsagePlan
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.InstanceID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.PushPerMin,
		&i.PushBurst,
		&i.PushDailyQuota,
	)
	return i, err
}

const getInstance = `-- name: GetInstance :one
SELECT id, app_id, label, enc_token_hash, created_at, usage_plan_id FROM instance WHERE id = ?
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Label,
		&i.EncTokenHash,
		&i.CreatedAt,
		&i.UsagePlanID,
	)
	return i, err
}

const getInstanceUsagePlan = `-- name: GetInstanceUsagePlan :one
SELECT id, app_id, instance_id, name, is_default, created_at, push_per_min, push_burst, push_daily_quota FROM instance_usage_plan WHERE id = ?
`

func (q *Queries) GetInstanceUsagePlan(ctx context.Context, id string) (InstanceUsagePlan, error) {
	row := q.db.QueryRowContext(ctx, getInstanceUsagePlan, id)
	var i InstanceUsagePlan
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.InstanceID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.PushPerMin,
		&i.PushBurst,
		&i.PushDailyQuota,
	)
	return i, err
}

const getServerSetting = `-- name: GetServerSetting :one
SELECT id, retry_max_attempts, retry_base_backoff, retry_max_backoff, auth_fail_ip_per_min, auth_fail_ip_burst FROM settings WHERE id = 1
`

func (q *Queries) GetServerSetting(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getServerSetting)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.RetryMaxAttempts,
		&i.RetryBaseBackoff,
		&i.RetryMaxBackoff,
		&i.AuthFailIpPerMin,
		&i.AuthFailIpBurst,
	)
	return i, err
}

const listAppCredentials = `-- name: ListAppCredentials :many
SELECT transport, enc_blob FROM app_credential WHERE app_id = ?1
`

type ListAppCredentialsRow struct {
	Transport string
	EncBlob   []byte
}

func (q *Queries) ListAppCredentials(ctx context.Context, appID string) ([]ListAppCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppCredentials, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppCredentialsRow
	for rows.Next() {
		var i ListAppCredentialsRow
		if err := rows.Scan(&i.Transport, &i.EncBlob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppUsagePlans = `-- name: ListAppUsagePlans :many
SELECT id, app_id, name, is_default, created_at, push_per_min, push_daily_quota, register_per_min, register_burst, register_ip_per_min, register_ip_burst, subscribe_per_min, subscribe_burst FROM app_usage_plan ORDER BY created_at
`

func (q *Queries) ListAppUsagePlans(ctx context.Context) ([]AppUsagePlan, error) {
	rows, err := q.db.QueryContext(ctx, listAppUsagePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUsagePlan
	for rows.Next() {
		var i AppUsagePlan
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.PushPerMin,
			&i.PushDailyQuota,
			&i.RegisterPerMin,
			&i.RegisterBurst,
			&i.RegisterIpPerMin,
			&i.RegisterIpBurst,
			&i.SubscribePerMin,
			&i.SubscribeBurst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
SELECT id, name, enc_token_hash, is_public, key_version, min_key_version, turnstile_site_key, enc_turnstile_secret, created_at, usage_plan_id FROM app ORDER BY created_at
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EncTokenHash,
			&i.IsPublic,
			&i.KeyVersion,
			&i.MinKeyVersion,
			&i.TurnstileSiteKey,
			&i.EncTurnstileSecret,
			&i.CreatedAt,
			&i.UsagePlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceUsagePlans = `-- name: ListInstanceUsagePlans :many
SELECT id, app_id, instance_id, name, is_default, created_at, push_per_min, push_burst, push_daily_quota FROM instance_usage_plan WHERE app_id = ?1 ORDER BY created_at
`

func (q *Queries) ListInstanceUsagePlans(ctx context.Context, appID string) ([]InstanceUsagePlan, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceUsagePlans, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceUsagePlan
	for rows.Next() {
		var i InstanceUsagePlan
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.InstanceID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.PushPerMin,
			&i.PushBurst,
			&i.PushDailyQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByApp = `-- name: ListInstancesByApp :many
SELECT id, app_id, label, enc_token_hash, created_at, usage_plan_id FROM instance WHERE app_id = ?1 ORDER BY created_at
`

func (q *Queries) ListInstancesByApp(ctx context.Context, appID string) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstancesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Label,
			&i.EncTokenHash,
			&i.CreatedAt,
			&i.UsagePlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageCountersForDay = `-- name: ListUsageCountersForDay :many
SELECT scope, count FROM usage_counter WHERE date = ?1
`

type ListUsageCountersForDayRow struct {
	Scope string
	Count int64
}

func (q *Queries) ListUsageCountersForDay(ctx context.Context, date types.Date) ([]ListUsageCountersForDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageCountersForDay, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageCountersForDayRow
	for rows.Next() {
		var i ListUsageCountersForDayRow
		if err := rows.Scan(&i.Scope, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppPublic = `-- name: SetAppPublic :execrows
UPDATE app SET is_public = ?1 WHERE id = ?2
`

type SetAppPublicParams struct {
	IsPublic bool
	ID       string
}

func (q *Queries) SetAppPublic(ctx context.Context, arg SetAppPublicParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAppPublic, arg.IsPublic, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAppToken = `-- name: SetAppToken :execrows
UPDATE app SET enc_token_hash = ?1 WHERE id = ?2
`

type SetAppTokenParams struct {
	EncTokenHash []byte
	ID           string
}

func (q *Queries) SetAppToken(ctx context.Context, arg SetAppTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAppToken, arg.EncTokenHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAppTurnstile = `-- name: SetAppTurnstile :execrows
UPDATE app SET turnstile_site_key = ?1, enc_turnstile_secret = ?2 WHERE id = ?3
`

type SetAppTurnstileParams struct {
	TurnstileSiteKey   types.NullString
	EncTurnstileSecret []byte
	ID                 string
}

func (q *Queries) SetAppTurnstile(ctx context.Context, arg SetAppTurnstileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAppTurnstile, arg.TurnstileSiteKey, arg.EncTurnstileSecret, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateApp = `-- name: UpdateApp :execrows
UPDATE app SET
  name = COALESCE(?1, name),
  is_public = COALESCE(?2, is_public)
WHERE id = ?3
`

type UpdateAppParams struct {
	Name     types.NullString
	IsPublic sql.NullBool
	ID       string
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateApp, arg.Name, arg.IsPublic, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAppKeyVersion = `-- name: UpdateAppKeyVersion :execrows
UPDATE app SET key_version = ?1, min_key_version = ?2 WHERE id = ?3
`

type UpdateAppKeyVersionParams struct {
	KeyVersion    int64
	MinKeyVersion int64
	ID            string
}

func (q *Queries) UpdateAppKeyVersion(ctx context.Context, arg UpdateAppKeyVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAppKeyVersion, arg.KeyVersion, arg.MinKeyVersion, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAppUsagePlan = `-- name: UpdateAppUsagePlan :execrows
UPDATE app_usage_plan SET
  name = COALESCE(?1, name),
  push_per_min = COALESCE(?2, push_per_min),
  push_daily_quota = COALESCE(?3, push_daily_quota),
  register_per_min = COALESCE(?4, register_per_min),
  register_burst = COALESCE(?5, register_burst),
  register_ip_per_min = COALESCE(?6, register_ip_per_min),
  register_ip_burst = COALESCE(?7, register_ip_burst),
  subscribe_per_min = COALESCE(?8, subscribe_per_min),
  subscribe_burst = COALESCE(?9, subscribe_burst)
WHERE id = ?10
`

type UpdateAppUsagePlanParams struct {
	Name             types.NullString
	PushPerMin       types.NullInt64
	PushDailyQuota   types.NullInt64
	RegisterPerMin   types.NullInt64
	RegisterBurst    types.NullInt64
	RegisterIpPerMin types.NullInt64
	RegisterIpBurst  types.NullInt64
	SubscribePerMin  types.NullInt64
	SubscribeBurst   types.NullInt64
	ID               string
}

func (q *Queries) UpdateAppUsagePlan(ctx context.Context, arg UpdateAppUsagePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAppUsagePlan,
		arg.Name,
		arg.PushPerMin,
		arg.PushDailyQuota,
		arg.RegisterPerMin,
		arg.RegisterBurst,
		arg.RegisterIpPerMin,
		arg.RegisterIpBurst,
		arg.SubscribePerMin,
		arg.SubscribeBurst,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInstance = `-- name: UpdateInstance :execrows
UPDATE instance SET
  label = COALESCE(?1, label)
WHERE id = ?2
`

type UpdateInstanceParams struct {
	Label types.NullString
	ID    string
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInstance, arg.Label, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInstanceTokenHash = `-- name: UpdateInstanceTokenHash :execrows
UPDATE instance SET enc_token_hash = ?1 WHERE id = ?2
`

type UpdateInstanceTokenHashParams struct {
	EncTokenHash []byte
	ID           string
}

func (q *Queries) UpdateInstanceTokenHash(ctx context.Context, arg UpdateInstanceTokenHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInstanceTokenHash, arg.EncTokenHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateInstanceUsagePlan = `-- name: UpdateInstanceUsagePlan :execrows
UPDATE instance_usage_plan SET
  name = COALESCE(?1, name),
  push_per_min = COALESCE(?2, push_per_min),
  push_burst = COALESCE(?3, push_burst),
  push_daily_quota = COALESCE(?4, push_daily_quota)
WHERE id = ?5
`

type UpdateInstanceUsagePlanParams struct {
	Name           types.NullString
	PushPerMin     types.NullInt64
	PushBurst      types.NullInt64
	PushDailyQuota types.NullInt64
	ID             string
}

func (q *Queries) UpdateInstanceUsagePlan(ctx context.Context, arg UpdateInstanceUsagePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInstanceUsagePlan,
		arg.Name,
		arg.PushPerMin,
		arg.PushBurst,
		arg.PushDailyQuota,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateServerSetting = `-- name: UpdateServerSetting :exec
UPDATE settings SET
  retry_max_attempts = COALESCE(?1, retry_max_attempts),
  retry_base_backoff = COALESCE(?2, retry_base_backoff),
  retry_max_backoff = COALESCE(?3, retry_max_backoff),
  auth_fail_ip_per_min = COALESCE(?4, auth_fail_ip_per_min),
  auth_fail_ip_burst = COALESCE(?5, auth_fail_ip_burst)
WHERE id = 1
`

type UpdateServerSettingParams struct {
	RetryMaxAttempts types.NullInt64
	RetryBaseBackoff types.NullString
	RetryMaxBackoff  types.NullString
	AuthFailIpPerMin types.NullInt64
	AuthFailIpBurst  types.NullInt64
}

func (q *Queries) UpdateServerSetting(ctx context.Context, arg UpdateServerSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateServerSetting,
		arg.RetryMaxAttempts,
		arg.RetryBaseBackoff,
		arg.RetryMaxBackoff,
		arg.AuthFailIpPerMin,
		arg.AuthFailIpBurst,
	)
	return err
}

const upsertAppCredential = `-- name: UpsertAppCredential :exec
INSERT INTO app_credential (app_id, transport, enc_blob)
VALUES (?1, ?2, ?3)
ON CONFLICT (app_id, transport) DO UPDATE SET enc_blob = excluded.enc_blob
`

type UpsertAppCredentialParams struct {
	AppID     string
	Transport string
	EncBlob   []byte
}

func (q *Queries) UpsertAppCredential(ctx context.Context, arg UpsertAppCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppCredential, arg.AppID, arg.Transport, arg.EncBlob)
	return err
}

const upsertUsageCounter = `-- name: UpsertUsageCounter :exec
INSERT INTO usage_counter (scope, date, count) VALUES (?1, ?2, ?3)
ON CONFLICT(scope, date) DO UPDATE SET count = excluded.count
`

type UpsertUsageCounterParams struct {
	Scope string
	Date  types.Date
	Count int64
}

func (q *Queries) UpsertUsageCounter(ctx context.Context, arg UpsertUsageCounterParams) error {
	_, err := q.db.ExecContext(ctx, upsertUsageCounter, arg.Scope, arg.Date, arg.Count)
	return err
}
