// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	types "github.com/MunifTanjim/pushport/internal/db/types"
)

type Querier interface {
	AssignAppUsagePlan(ctx context.Context, arg AssignAppUsagePlanParams) (int64, error)
	AssignInstanceUsagePlan(ctx context.Context, arg AssignInstanceUsagePlanParams) (int64, error)
	ClearAppTurnstile(ctx context.Context, id string) (int64, error)
	CountApps(ctx context.Context) (int64, error)
	CountInstances(ctx context.Context) (int64, error)
	CreateApp(ctx context.Context, arg CreateAppParams) error
	CreateAppUsagePlan(ctx context.Context, arg CreateAppUsagePlanParams) error
	CreateDefaultAppUsagePlan(ctx context.Context, arg CreateDefaultAppUsagePlanParams) error
	CreateDefaultInstanceUsagePlan(ctx context.Context, arg CreateDefaultInstanceUsagePlanParams) error
	CreateInstance(ctx context.Context, arg CreateInstanceParams) error
	CreateInstanceUsagePlan(ctx context.Context, arg CreateInstanceUsagePlanParams) error
	DeleteAppCredential(ctx context.Context, arg DeleteAppCredentialParams) error
	DeleteAppUsagePlan(ctx context.Context, id string) (int64, error)
	DeleteInstance(ctx context.Context, id string) (int64, error)
	DeleteInstanceUsagePlan(ctx context.Context, arg DeleteInstanceUsagePlanParams) (int64, error)
	DeleteUsageCountersBefore(ctx context.Context, date types.Date) error
	GetApp(ctx context.Context, id string) (App, error)
	GetAppUsagePlan(ctx context.Context, id string) (AppUsagePlan, error)
	GetDefaultAppUsagePlan(ctx context.Context) (AppUsagePlan, error)
	GetDefaultInstanceUsagePlan(ctx context.Context, appID string) (InstanceUsagePlan, error)
	GetInstance(ctx context.Context, id string) (Instance, error)
	GetInstanceUsagePlan(ctx context.Context, id string) (InstanceUsagePlan, error)
	GetServerSetting(ctx context.Context) (Setting, error)
	ListAppCredentials(ctx context.Context, appID string) ([]ListAppCredentialsRow, error)
	ListAppUsagePlans(ctx context.Context) ([]AppUsagePlan, error)
	ListApps(ctx context.Context) ([]App, error)
	ListInstanceUsagePlans(ctx context.Context, appID string) ([]InstanceUsagePlan, error)
	ListInstancesByApp(ctx context.Context, appID string) ([]Instance, error)
	ListUsageCountersForDay(ctx context.Context, date types.Date) ([]ListUsageCountersForDayRow, error)
	SetAppPublic(ctx context.Context, arg SetAppPublicParams) (int64, error)
	SetAppToken(ctx context.Context, arg SetAppTokenParams) (int64, error)
	SetAppTurnstile(ctx context.Context, arg SetAppTurnstileParams) (int64, error)
	UpdateApp(ctx context.Context, arg UpdateAppParams) (int64, error)
	UpdateAppKeyVersion(ctx context.Context, arg UpdateAppKeyVersionParams) (int64, error)
	UpdateAppUsagePlan(ctx context.Context, arg UpdateAppUsagePlanParams) (int64, error)
	UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (int64, error)
	UpdateInstanceTokenHash(ctx context.Context, arg UpdateInstanceTokenHashParams) (int64, error)
	UpdateInstanceUsagePlan(ctx context.Context, arg UpdateInstanceUsagePlanParams) (int64, error)
	UpdateServerSetting(ctx context.Context, arg UpdateServerSettingParams) error
	UpsertAppCredential(ctx context.Context, arg UpsertAppCredentialParams) error
	UpsertUsageCounter(ctx context.Context, arg UpsertUsageCounterParams) error
}

var _ Querier = (*Queries)(nil)
